server:
  port: 8222
spring:
  cloud:
    gateway:
      globalcors:
        enabled: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/colors/**, /api/v1/categories/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    authenticationServiceUri: http://auth-service/api/v1/auth/verify
    publicUrls:
      - api/v1/auth/login
      - api/v1/auth/register
      - api/v1/auth/verify

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG